# Generated by Django 4.1.7 on 2023-04-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_post_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='news', verbose_name='Постер'),
        ),
    ]
