# Generated by Django 4.1.7 on 2023-04-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0003_author_status_alter_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='groups',
            field=models.ManyToManyField(to='auth.group'),
        ),
    ]
